# buildspec.yml (프론트엔드용)
version: 0.2
phases:
  install:
    runtime-versions:
        # Node.js 런타임 버전을 명시 (매우 중요)
        nodejs: 20
    commands:
      # Node.js 환경 설정
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      # 백엔드 API URL 환경 변수 설정
      - echo "REACT_APP_API_URL=https://yourdomain.com" > .env.production
  build:
    commands:
      # 프로덕션 빌드 실행
      - echo Building frontend...
      - npm run build
  post_build:
    commands:
      # 1. S3에 빌드된 파일 업로드 (배포)
      - echo Deploying to S3...
      - aws s3 sync build/ s3://jibijoa-frontend/ --delete
      # 2. CloudFront 캐시 무효화 (필수)
      # 캐시 무효화 ID를 CloudFront Console에서 확인하여 대체해야 함
      - aws cloudfront create-invalidation --distribution-id E2AR8YMUY8M22M --paths "/*"
artifacts:
  files:
    # 빌드 결과물은 S3에 직접 배포하므로 아티팩트는 필요 없음
    - '**/*'